name: inno_ft
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  flutter_riverpod: ^2.0.0
  image_picker: ^0.8.4+8
  http: ^0.13.6
  provider: ^6.1.2
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
